<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
require_once '/usr/share/php/Fedora/Autoloader'.'/autoload.php';

\Fedora\Autoloader\Autoload::addClassMap(
    array(
        'os_guess' => '/../OS/Guess.php',
                'pear' => '/../PEAR.php',
                'pear_builder' => '/Builder.php',
                'pear_channelfile' => '/ChannelFile.php',
                'pear_channelfile_parser' => '/ChannelFile/Parser.php',
                'pear_command' => '/Command.php',
                'pear_command_auth' => '/Command/Auth.php',
                'pear_command_build' => '/Command/Build.php',
                'pear_command_channels' => '/Command/Channels.php',
                'pear_command_common' => '/Command/Common.php',
                'pear_command_config' => '/Command/Config.php',
                'pear_command_install' => '/Command/Install.php',
                'pear_command_mirror' => '/Command/Mirror.php',
                'pear_command_package' => '/Command/Package.php',
                'pear_command_pickle' => '/Command/Pickle.php',
                'pear_command_registry' => '/Command/Registry.php',
                'pear_command_remote' => '/Command/Remote.php',
                'pear_command_test' => '/Command/Test.php',
                'pear_common' => '/Common.php',
                'pear_config' => '/Config.php',
                'pear_dependency2' => '/Dependency2.php',
                'pear_dependencydb' => '/DependencyDB.php',
                'pear_downloader' => '/Downloader.php',
                'pear_downloader_package' => '/Downloader/Package.php',
                'pear_error' => '/../PEAR.php',
                'pear_errorstack' => '/ErrorStack.php',
                'pear_exception' => '/Exception.php',
                'pear_frontend' => '/Frontend.php',
                'pear_frontend_cli' => '/Frontend/CLI.php',
                'pear_installer' => '/Installer.php',
                'pear_installer_role' => '/Installer/Role.php',
                'pear_installer_role_cfg' => '/Installer/Role/Cfg.php',
                'pear_installer_role_common' => '/Installer/Role/Common.php',
                'pear_installer_role_data' => '/Installer/Role/Data.php',
                'pear_installer_role_doc' => '/Installer/Role/Doc.php',
                'pear_installer_role_ext' => '/Installer/Role/Ext.php',
                'pear_installer_role_man' => '/Installer/Role/Man.php',
                'pear_installer_role_php' => '/Installer/Role/Php.php',
                'pear_installer_role_script' => '/Installer/Role/Script.php',
                'pear_installer_role_src' => '/Installer/Role/Src.php',
                'pear_installer_role_test' => '/Installer/Role/Test.php',
                'pear_installer_role_www' => '/Installer/Role/Www.php',
                'pear_packagefile' => '/PackageFile.php',
                'pear_packagefile_generator_v1' => '/PackageFile/Generator/v1.php',
                'pear_packagefile_generator_v2' => '/PackageFile/Generator/v2.php',
                'pear_packagefile_parser_v1' => '/PackageFile/Parser/v1.php',
                'pear_packagefile_parser_v2' => '/PackageFile/Parser/v2.php',
                'pear_packagefile_v1' => '/PackageFile/v1.php',
                'pear_packagefile_v2' => '/PackageFile/v2.php',
                'pear_packagefile_v2_rw' => '/PackageFile/v2/rw.php',
                'pear_packagefile_v2_validator' => '/PackageFile/v2/Validator.php',
                'pear_packager' => '/Packager.php',
                'pear_proxy' => '/Proxy.php',
                'pear_registry' => '/Registry.php',
                'pear_rest' => '/REST.php',
                'pear_rest_10' => '/REST/10.php',
                'pear_rest_11' => '/REST/11.php',
                'pear_rest_13' => '/REST/13.php',
                'pear_runtest' => '/RunTest.php',
                'pear_task_common' => '/Task/Common.php',
                'pear_task_postinstallscript' => '/Task/Postinstallscript.php',
                'pear_task_postinstallscript_rw' => '/Task/Postinstallscript/rw.php',
                'pear_task_replace' => '/Task/Replace.php',
                'pear_task_replace_rw' => '/Task/Replace/rw.php',
                'pear_task_unixeol' => '/Task/Unixeol.php',
                'pear_task_unixeol_rw' => '/Task/Unixeol/rw.php',
                'pear_task_windowseol' => '/Task/Windowseol.php',
                'pear_task_windowseol_rw' => '/Task/Windowseol/rw.php',
                'pear_validate' => '/Validate.php',
                'pear_validator_pecl' => '/Validator/PECL.php',
                'pear_xmlparser' => '/XMLParser.php',
                'system' => '/../System.php',
    ),
    __DIR__
);
// @codeCoverageIgnoreEnd
