#!/bin/bash
if [[ -x /usr/libexec/grubby/grubby ]] ; then
	exec /usr/libexec/grubby/grubby "${@}"
elif [[ -x /usr/libexec/grubby/grubby-bls ]] ; then
	exec /usr/libexec/grubby/grubby-bls "${@}"
fi
echo "Grubby is not installed correctly." >>/dev/stderr
exit 1
